name: job_scraper
on:
  schedule:
    # Runs at 6:00 AM IST (00:30 UTC) every day
    - cron: '30 0 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 nbconvert jupyter
        
    - name: Convert notebook to Python script
      run: |
        jupyter nbconvert --to script daily_job_digest.ipynb --output daily_job_digest
        
    - name: Run job scraper
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python daily_job_digest.py
        
    - name: Upload any output files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-scraper-output
        path: |
          *.log
          *.txt
          *.json
          *.csv
          *.html
        if-no-files-found: ignore
