name: job_scraper
on:
  schedule:
    # Runs at 6:00 AM IST (00:30 UTC) every day
    - cron: '30 0 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        # Optional: Install Selenium if you want to use it
        # pip install selenium webdriver-manager
        
    - name: Install Chrome for Selenium (optional)
      run: |
        # Uncomment these lines if you want to use Selenium
        # sudo apt-get update
        # sudo apt-get install -y google-chrome-stable
        
    - name: Run job scraper
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python enhanced_job_scraper.py
        
    - name: Upload logs (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job-scraper-logs
        path: |
          *.log
          *.txt
